"""Attack interfaces and execution flow."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Sequence

from backend.models.attack_result import AttackResult, AttackStatus
from backend.models.conversation import Conversation
from backend.prompt.normalizer import PromptNormalizer
from backend.scoring.scorer import Scorer
from backend.targets.base_target import TargetAdapter


@dataclass(frozen=True, slots=True)
class AttackPrompt:
    """A normalized attack candidate generated by a strategy."""

    text: str
    category: str
    technique: str
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class AttackRequest:
    """Input to an attack run."""

    objective: str
    max_attempts: int = 5
    conversation: Conversation = field(default_factory=Conversation)
    metadata: dict[str, Any] = field(default_factory=dict)


class AttackStrategy(ABC):
    """Strategy interface for any LLM security attack."""

    name: str
    category: str

    @abstractmethod
    def build_prompts(self, request: AttackRequest) -> Sequence[AttackPrompt]:
        """Return attack prompts for the given request."""


class AttackExecutor:
    """Executes a strategy against a target through normalized prompts."""

    def __init__(
        self,
        target: TargetAdapter,
        scorer: Scorer,
        normalizer: PromptNormalizer | None = None,
    ) -> None:
        self.target = target
        self.scorer = scorer
        self.normalizer = normalizer or PromptNormalizer()

    async def run(self, strategy: AttackStrategy, request: AttackRequest) -> list[AttackResult]:
        results: list[AttackResult] = []
        prompts = list(strategy.build_prompts(request))[: request.max_attempts]

        for prompt in prompts:
            conversation = request.conversation.copy_with_messages()
            normalized = self.normalizer.normalize(prompt.text)
            conversation.add("user", normalized, attack=strategy.name, technique=prompt.technique)

            try:
                response_message = await self.target.send(conversation.messages)
                score = self.scorer.score(prompt=normalized, response=response_message.content)
                status = AttackStatus.FAILED if score.is_vulnerable else AttackStatus.PASSED
                response = response_message.content
                metadata = {**prompt.metadata, **response_message.metadata}
            except Exception as exc:
                score = self.scorer.error_score(str(exc))
                status = AttackStatus.ERROR
                response = ""
                metadata = {**prompt.metadata, "error": str(exc)}

            results.append(
                AttackResult(
                    attack_name=strategy.name,
                    category=prompt.category,
                    prompt=normalized,
                    response=response,
                    score=score,
                    status=status,
                    metadata=metadata,
                )
            )

        return results

